# Copyright 2020 Tampere University
# This software was developed as a part of the CityIoT project: https://www.cityiot.fi/english
# This source code is licensed under the 3-clause BSD license. See license.txt in the repository root directory.
# Author(s): Ville Heikkilä <ville.heikkila@tuni.fi>

version: '3.5'

services:

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-6.5.3}
    depends_on:
      - ${UTIL_STACK_NAME:-util}_${POSTGRES_SERVICE_URI:-postgresdb}
    env_file:
      - ./env/grafana.env
      - ./env/secrets/grafana.env
    # entrypoint:
    #   - /wait-for-it.sh
    #   - ${POSTGRES_SERVICE_URI:-postgresdb}:${POSTGRES_PORT:-5432}
    #   - --timeout=${WAIT_FOR_IT_TIMEOUT:-300}
    #   - --
    #   - /run.sh
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
    # uncomment the following when not using subdomains
    # ports:
    #   - target: ${GRAFANA_PORT:-3000}
    #     published: ${GRAFANA_PORT:-3000}
    #     mode: host
    #     protocol: tcp
    volumes:
      - grafanadata:/var/lib/grafana
      - grafanaconfig:/etc/grafana
      # - type: bind
      #   source: ./scripts/wait-for-it.sh
      #   target: /wait-for-it.sh
      #   read_only: true
    networks:
      - cityiot

volumes:
  grafanadata:
    external: true
    name: grafana_data
  grafanaconfig:
    external: true
    name: grafana_config

networks:
  cityiot:
    driver: overlay
    external: true
    name: ${CITYIOT_NETWORK_NAME:-cityiot}
