# Copyright 2020 Tampere University
# This software was developed as a part of the CityIoT project: https://www.cityiot.fi/english
# This source code is licensed under the 3-clause BSD license. See license.txt in the repository root directory.
# Author(s): Ville Heikkilä <ville.heikkila@tuni.fi>

version: '3.5'

services:

  wirecloud:
    image: ${WIRECLOUD_IMAGE:-fiware/wirecloud:1.3}
    depends_on:
      - ${UTIL_STACK_NAME:-util}_${POSTGRES_SERVICE_URI:-postgresdb}
      - ${UTIL_STACK_NAME:-util}_${ELASTICSEARCH_SERVICE_URI:-elasticsearch}
      - ${UTIL_STACK_NAME:-util}_${MEMCACHED_SERVICE_URI:-memcached}
    env_file:
      - ./env/wirecloud.env
      - ./env/secrets/wirecloud.env
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
    # uncomment the following when not using subdomains
    # ports:
    #   - target: ${WIRECLOUD_PORT:-8000}
    #     published: ${WIRECLOUD_PORT:-8000}
    #     mode: host
    #     protocol: tcp
    entrypoint:
      - /wait-for-it.sh
      - ${POSTGRES_SERVICE_URI:-postgresdb}:${POSTGRES_PORT:-5432}
      - --timeout=${WAIT_FOR_IT_TIMEOUT:-300}
      - --
      - /wait-for-it.sh
      - ${ELASTICSEARCH_SERVICE_URI:-elasticsearch}:${ELASTICSEARCH_PORT:-9200}
      - --timeout=${WAIT_FOR_IT_TIMEOUT:-300}
      - --
      - /wait-for-it.sh
      - ${MEMCACHED_SERVICE_URI:-memcached}:${MEMCACHED_PORT:-11211}
      - --timeout=${WAIT_FOR_IT_TIMEOUT:-300}
      - --
      - /docker-entrypoint.sh
      - python
      - manage.py
      - collectstatic
    volumes:
      - wireclouddata:/opt/wirecloud_instance/data
      - wirecloudstatic:/var/www/static
      - type: bind
        source: ./scripts/wait-for-it.sh
        target: /wait-for-it.sh
        read_only: true
    networks:
      - cityiot

volumes:
  wireclouddata:
    external: true
    name: wirecloud_data
  wirecloudstatic:
    external: true
    name: wirecloud_static

networks:
  cityiot:
    driver: overlay
    external: true
    name: ${CITYIOT_NETWORK_NAME:-cityiot}
