# Copyright 2019 Tampere University
# This software was developed as a part of the CityIoT project: https://www.cityiot.fi/english
# This source code is licensed under the 3-clause BSD license. See license.txt in the repository root directory.
# Author(s): Ville Heikkilä <ville.heikkila@tuni.fi>

version: '3.5'

services:

  nginx:
    image: nginx:${NGINX_VERSION:-1.15.8}
    ports:
      - target: 80
        published: 80
        mode: host
        protocol: tcp
      - target: 443
        published: 443
        mode: host
        protocol: tcp
    secrets:
      - certificate
      - dhparams
      - private_key
      - proxy_keys.conf
      - users.conf
      - services.conf
    deploy:
      mode: global
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 30s
    volumes:
      - ./nginx:/etc/nginx:ro
      - wirecloudstatic:/var/www/static:ro
    command: [nginx, '-g', 'daemon off;']
    networks:
      - cityiot

volumes:
  wirecloudstatic:
    external: true
    name: wirecloud_static

secrets:
  certificate:
    file: ./secrets/chained.pem
  dhparams:
    file: ./secrets/dhparam.pem
  private_key:
    file: ./secrets/domain.key
  proxy_keys.conf:
    file: ./secrets/proxy_keys.conf
  users.conf:
    file: ./secrets/users.conf
  services.conf:
    file: ./secrets/services.conf

networks:
  cityiot:
    external: true
    name: ${CITYIOT_NETWORK_NAME:-cityiot}
